# Generated by Django 4.2.5 on 2024-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_questionsquizrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('pronounciation', models.CharField(max_length=255, null=True)),
                ('correct_url', models.CharField(max_length=300)),
                ('url1', models.CharField(max_length=300)),
                ('url2', models.CharField(max_length=300)),
                ('url3', models.CharField(max_length=300)),
                ('diff', models.CharField(choices=[('easy', 'Beginner'), ('medium', 'Elementary'), ('hard', 'Intermediate')], max_length=6)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ja', 'Japanese'), ('hi', 'Hindi')], max_length=2)),
                ('repeated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('correct_alt', models.CharField(max_length=255)),
                ('pronounciation', models.CharField(max_length=255, null=True)),
                ('alt1', models.CharField(max_length=255)),
                ('alt2', models.CharField(max_length=255)),
                ('alt3', models.CharField(max_length=255)),
                ('diff', models.CharField(choices=[('easy', 'Beginner'), ('medium', 'Elementary'), ('hard', 'Intermediate')], max_length=6)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ja', 'Japanese'), ('hi', 'Hindi')], max_length=2)),
                ('repeated', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionsquizrelation',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionsquizrelation',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='QuestionsQuizRelation',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
