# Generated by Django 4.2.4 on 2024-03-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
    ]
