# Generated by Django 4.2.4 on 2024-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='purpose',
            field=models.TextField(max_length=100),
        ),
    ]
