# Generated by Django 4.2.4 on 2024-04-02 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_community_image_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(default=1, related_name='Members', to=settings.AUTH_USER_MODEL),
        ),
    ]
