# Generated by Django 4.2.4 on 2024-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
