# Generated by Django 5.0.3 on 2024-03-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_src_lang_user_target_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='src_lang',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_lang',
            field=models.CharField(max_length=20),
        ),
    ]
